# Generated by Django 4.1.2 on 2022-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_restaurant_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
