# Generated by Django 4.1.2 on 2022-11-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_cover_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="addres_line",
            new_name="address",
        ),
    ]
