# Generated by Django 4.1.2 on 2022-11-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_addres_line_userprofile_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="pin_code",
            new_name="zip_code",
        ),
    ]
